<a href="https://colab.research.google.com/github/tanmaykhanna07/python-for-data-science/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
server_logs = {
    "Timestamp": ["10:00", "10:05", "10:10", "10:15", "10:20"],
    "Endpoint": ["/login", "/get_habits", "/login", "/update_habit", "/get_habits"],
    "Status_Code": [200, 200, 401, 500, 200],
    "Response_Time_ms": [45, 120, 30, 850, 110]
}

df = pd.DataFrame(server_logs)

df

  Timestamp       Endpoint  Status_Code  Response_Time_ms
0     10:00         /login          200                45
1     10:05    /get_habits          200               120
2     10:10         /login          401                30
3     10:15  /update_habit          500               850
4     10:20    /get_habits          200               110

In [3]:
response_times = df['Response_Time_ms']
print(response_times)

0     45
1    120
2     30
3    850
4    110
Name: Response_Time_ms, dtype: int64

In [4]:
is_crash = df['Status_Code'] == 500
crashed_requests = df[is_crash]
print(crashed_requests)

  Timestamp       Endpoint  Status_Code  Response_Time_ms
3     10:15  /update_habit          500               850

In [5]:
#industry standard of [4]

crashed_requests = df[df['Status_Code'] == 500]
print(crashed_requests)

  Timestamp       Endpoint  Status_Code  Response_Time_ms
3     10:15  /update_habit          500               850

In [6]:
endpoint_performance = df.groupby('Endpoint')['Response_Time_ms'].mean()

print("Average Response Time per Endpoint (ms):")
print(endpoint_performance)

Average Response Time per Endpoint (ms):
Endpoint
/get_habits      115.0
/login            37.5
/update_habit    850.0
Name: Response_Time_ms, dtype: float64

In [7]:
#Feature Engineering - create new data out of old data
df['Is_Slow'] = df['Response_Time_ms'] > 100

sorted_requests = df.sort_values(by='Response_Time_ms', ascending= False)

sorted_requests

  Timestamp       Endpoint  Status_Code  Response_Time_ms  Is_Slow
3     10:15  /update_habit          500               850     True
1     10:05    /get_habits          200               120     True
4     10:20    /get_habits          200               110     True
0     10:00         /login          200                45    False
2     10:10         /login          401                30    False

In [8]:
checkout_data = {
    "User_ID": [101, 102, 101, 103, 102, 101],
    "Item": ["Mechanical Keyboard", "Monitor", "Mouse", "Laptop", "Headset", "Mousepad"],
    "Price": [150, 300, 50, 1200, 80, 20],
    "Status": ["Success", "Failed", "Success", "Success", "Success", "Failed"]
}

df_sales = pd.DataFrame(checkout_data)
df_sales

   User_ID                 Item  Price   Status
0      101  Mechanical Keyboard    150  Success
1      102              Monitor    300   Failed
2      101                Mouse     50  Success
3      103               Laptop   1200  Success
4      102              Headset     80  Success
5      101             Mousepad     20   Failed

In [9]:
total_revenue_by_user = df_sales.groupby('User_ID')['Price'].sum()
total_revenue_by_user

User_ID
101     220
102     380
103    1200
Name: Price, dtype: int64

In [10]:
successfull_purchases = df_sales[df_sales['Status'] == "Success"]
total = successfull_purchases.groupby('User_ID')['Price'].sum()
total

User_ID
101     200
102      80
103    1200
Name: Price, dtype: int64

In [11]:
failed_purchases = df_sales[df_sales['Status'] == "Failed"]
failed_purchases

   User_ID      Item  Price  Status
1      102   Monitor    300  Failed
5      101  Mousepad     20  Failed

In [12]:
df_sales['Is_Expensive'] = df_sales['Price'] >= 100
sorted_df = df_sales.sort_values(by = "Price" , ascending = False)
sorted_df

   User_ID                 Item  Price   Status  Is_Expensive
3      103               Laptop   1200  Success          True
1      102              Monitor    300   Failed          True
0      101  Mechanical Keyboard    150  Success          True
4      102              Headset     80  Success         False
2      101                Mouse     50  Success         False
5      101             Mousepad     20   Failed         False